#!/bin/bash
# installs and configures nginx for our web-01 server
apt update
apt install -y nginx
echo '
server {
    listen 80;
    location / {
        return 200 "Hello World!";
    }
}' | tee /etc/nginx/sites-available/default
service nginx restart
