#!/usr/bin/env bash

# Update package repositories and install Nginx
apt update
apt install -y nginx

# Configure Nginx
echo '
server {
    listen 80;
    location / {
        return 200 "Hello World!";
    }
}' | tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx using the init.d script
service nginx restart
