#!/usr/bin/env bash
# Installs and configures Nginx on our web-01 server:
apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/nginx/html/FourOhFour.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/FourOhFour.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

    location /redirect_me {
        return 301 https://example.com/;

    error_page 404 /FourOhFour.html;
    location /404 {
        root /etc/nginx/FourOhFour;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
