#!/usr/bin/env bash
# Installs and configures Nginx on web-02 server:
apt-get update
apt-get install -y nginx
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     add_header X-Served-By \$hostname;
}
" > /etc/nginx/sites-available/default
service nginx restart
