#!/usr/bin/env bash
# installs and configures HAProxy on lb-01 server
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get install -y haproxy=2.8.\*
cat <<EOT >> /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 52.87.231.96 check
    server web-02 100.25.109.11 check
EOT
wget -O /etc/init.d/haproxy https://raw.githubusercontent.com/haproxy/haproxy/v2.4/examples/haproxy.init
chmod +x /etc/init.d/haproxy
update-rc.d haproxy defaults
service haproxy restart
