#!/usr/bin/env bash
# This script prints "Best School" 8 times, prints "bad luck" on
# the 4th line and "good luck" on the 8th line
i=0;
while [ $i -lt 10 ]; do
    if [ $i -eq 3 ]; then
        echo "bad luck";
    elif [ $i -eq 7 ]; then
        echo "good luck";
    else
        echo "Best School";
    fi;
    i=$((i+1))
done
