#!/usr/bin/env bash
# This script prints the numbers 1 to 20 with additional instructions
# for specific numbers
i=1
while [ $i -le 20 ]; do
    case $i in
        4)
            echo -e "$i\nbad luck from China"
            ;;
        9)
            echo -e "$i\nbad luck from Japan"
            ;;
        17)
            echo -e "$i\nbad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
    i=$((i+1))
done
