#!/usr/bin/env bash
# prints hours and minutes of the clock
i=0;
while [ $i -le 12 ]; do
    echo "Hour: $i";
    j=1;
    while [ $j -le 59 ]; do
        echo "$j"
        j=$((j+1));
    done
    i=$((i+1));
done
