#!/usr/bin/env bash
if [[ $(ps -o user= -p $(pgrep nginx)) != "nginx" ]]; then
    sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
    chown -R nginx:nginx /var/log/nginx /var/lib/nginx
    service nginx restart
fi
sed -i '/listen\s*80;/a \    listen 8080;' /etc/nginx/sites-available/default
service nginx reload
